# Generated by Django 4.1.5 on 2023-01-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
    ]
